name: Python Tests

on:
  push:
    branches:
      - main
      - maint/*
  pull_request:
    branches:
      - main
      - maint/*
  # Allow job to be triggered manually from GitHub interface
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Find and run scripts
        run: |
          find . -name "*.py" ! -path "./.*/*" ! -name "setup.py" | while read file; do
            echo "Running $file..."
            python "$file" --help > /dev/null || echo "$file exited with error code $?"
          done
